FROM node:18-alpine

# Dossier de l'app
WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install --production

# Copier le reste du code
COPY . .

# L'app écoute sur le port 3000
ENV PORT=3000
EXPOSE 3000

# Commande de démarrage
CMD ["npm", "start"]
